### ISSUE TITLE
Rename NPM package to kubo

### ISSUE THREAD

**Issue by lidel** [ipfs/npm-kubo#51]
> Part of https://github.com/ipfs/go-ipfs/issues/8959

## TODO

- [x] see if we can get `kubo` on NPM – tracked in  https://github.com/queerviolet/werkit/issues/1 (if it does not work out, we could go with `kubo-bin`)
- [x] decide if we want to do dual-publishing to both  names, or deprecate old one
- [ ] update CI to publish to new name

**Comment by lidel** [comment]
We now have https://www.npmjs.com/package/kubo and I've invited  `npm-service-account-ipfs` to be one of the maintainers.

I don' think dual-publishing is worth it, as it would require additional  code that modifies package.json in between builds.
Let's switch to a new name, and once Kubo 0.23 ships, deprecate the `go-ipfs` with message asking people to switch to `kubo`. 

I'll PR shortly.
